sudo: false
language: python
python:
  - 3.6
before_script:
  - git clone https://github.com/flutter/flutter.git --branch master --depth 1
  - export PATH=$(pwd)/flutter/bin:$(pwd)/flutter/bin/cache/dart-sdk/bin:$PATH
script:
  - flutter config --enable-web
  - flutter doctor --verbose
  - flutter test
  - flutter build web
deploy:
  provider: gcs
  skip_cleanup: true
  access_key_id: GOOG1EBKQ2DIPTQYJSQBZPSTD3OGWIYZQPAGJPWVH42GPE5AIOVQUNQ4Q5TCI
  secret_access_key:
    secure: Tbjwf4rfvEGAbwapKX8XnT+qokNEBBeSkQ4J+XRYJbUn55RwnuJU8FGsdRGJ3BVTb3G8H88dJ40Ond8j2BQY+UFbqfuq7pN322dX+emqfjUzPdPOBgLinGGe9nl/JivCcitKq4KIfQGmi95klx4VhvzOebArdJVMh66ZeftiunlvBRSZx6VTJFtH5zBcSCRS3naFJSOHGHMg7PQYqtKmIOODzEo7vTM9Y9xfehl0zr75dGy26n6FBAcDxC2hfzJqXUYIErYfN2VA3CtjRheEVK/YLKCbeziDOSKB3Kud2gRKRwPJrO8G10/Y9H+fCHT2udxxr/GtXvCKhhtFb7R5pFkJHby1q68y9jRZIiFzypa2isZO9nKuYocWFjwnt5YPeJkWkE1HsX13d2LckETIh8fG2lisswCDanKKnrbwsRWLhgTV3M9xueW0CC0YW9FjkRYHqe+B1XRIn5EMdks6cyD8qD0ozrBSYkaowTHRv4FTK0wzQXJGyQAhMbf2iHP1yuDXSbPSn+Tpa73jstyxWK6RAPZO0ZWo/09cXSPB+y/YohjNlwnaE0by6QGZ9mcOrvpddwUU1sgDBuaBQTL/hDXy7p75tGWwWZGZHn1bO+/xPI3JWgSkRxW4gI8dtEWAQFgMoEP8U+ym+mtDrQnJn4yuPcxUZ0DlNUchFpwbacs=
    bucket: yiws-io-archive
    local-dir: build/web
    on:
      repo: yiwensong/yiws_io
